### ISSUE TITLE
[Setting] 프로젝트 초기 세팅

### ISSUE THREAD

**Issue by HELLOHIDI** [sopkathon-32nd-10/iOS#1]
## 🛠 Issue
- 프로젝트 초기 세팅

## 📋 To-do
- [x] 폴더링
- [x] Issue, Pull Request 템플릿 생성
- [x] gitignore 파일 생성
- [x] Storyboard 파일 삭제
- [x] Extension 파일 추가
- [x] 라이브러리 추가
